/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author KamillaKisova
 */
public class KontrolovacRetazcov extends javax.swing.JFrame {

    /**
     * Creates new form KontrolovacRetazcov
     */
    public KontrolovacRetazcov() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        retazecLabel = new javax.swing.JLabel();
        velkeMaleToggleButton = new javax.swing.JToggleButton();
        regexLabel = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        ignorovanieToggleButton = new javax.swing.JToggleButton();
        trimCleanButton = new javax.swing.JButton();
        cheatsheetButton = new javax.swing.JButton();
        checkButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textArea.setColumns(20);
        textArea.setRows(5);
        scrollPane.setViewportView(textArea);

        panel.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 360, 100));

        retazecLabel.setText("Reťazec:");
        panel.add(retazecLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        velkeMaleToggleButton.setText("Case insensitive");
        panel.add(velkeMaleToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, -1));

        regexLabel.setText("Regulárny výraz:");
        panel.add(regexLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        panel.add(textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 300, -1));

        ignorovanieToggleButton.setText("Ignorovanie špeciálnych znakov");
        panel.add(ignorovanieToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 200, -1));

        trimCleanButton.setText("Trim & clean");
        trimCleanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                trimCleanButtonMouseReleased(evt);
            }
        });
        panel.add(trimCleanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        cheatsheetButton.setText("?");
        cheatsheetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cheatsheetButtonMouseReleased(evt);
            }
        });
        panel.add(cheatsheetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 40, -1));

        checkButton.setText("Check");
        checkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkButtonMouseReleased(evt);
            }
        });
        panel.add(checkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 70, -1));
        panel.add(resultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 70, 20));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkButtonMouseReleased
        
        String regex = textField.getText();
        String text = textArea.getText();
        StringBuilder text2 = new StringBuilder();
        if (ignorovanieToggleButton.isSelected()) {
            for (int i = 0; i < 10; i++) {
                char c = text.charAt(i);
                if (Character.isAlphabetic(c) || Character.isDigit(c))
                    text2.append(c);
            }
            text = text2.toString();
        }
        
        Pattern pattern;
        Matcher matcher;
        if (velkeMaleToggleButton.isSelected())
            pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
        else 
            pattern = Pattern.compile(regex);
        
        matcher = pattern.matcher(text);
        boolean matchFound = matcher.find();
        if (matchFound) {
            resultLabel.setText("OK");
        } else {
            resultLabel.setText("NG");
        }
    }//GEN-LAST:event_checkButtonMouseReleased

    private void trimCleanButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trimCleanButtonMouseReleased

        String text = textArea.getText();
        StringBuilder strBuilder = new StringBuilder();
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            if (!Character.isWhitespace(c) && !Character.isISOControl(c)) 
                strBuilder.append(c);
        }
        textArea.setText(strBuilder.toString());
    }//GEN-LAST:event_trimCleanButtonMouseReleased

    private void cheatsheetButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cheatsheetButtonMouseReleased
        
        new cheatsheet().setVisible(true);
    }//GEN-LAST:event_cheatsheetButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KontrolovacRetazcov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KontrolovacRetazcov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KontrolovacRetazcov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KontrolovacRetazcov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KontrolovacRetazcov().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cheatsheetButton;
    private javax.swing.JButton checkButton;
    private javax.swing.JToggleButton ignorovanieToggleButton;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel regexLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel retazecLabel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField textField;
    private javax.swing.JButton trimCleanButton;
    private javax.swing.JToggleButton velkeMaleToggleButton;
    // End of variables declaration//GEN-END:variables
}
